model:
    type: fast
    kernel_loss: 
        loss_fn: auf_loss
        ohem: false
    text_loss: 
        loss_fn: auf_loss
        ohem: false
data:
    batch_size: 16
    dataset: icdar2015
train:
    lr: 1e-3
    min_lr: 1e-5
    num_iterations: 100000
    train_eval_interval: 50
    val_eval_interval: null
    save_interval: 1000
    optimizer: adamw
    schedule: cosine_warmup
    warmup_iterations: 3000
    checkpoint: null
    resume: null