model:
    type: fast
    loss: balanced_bce_loss
data:
    batch_size: 16
    type: icdar2015
    datadir: ./data
train:
    lr: 1e-3
    epochs: 1200
    optimizer: adamw
    schedule: poly
    save_interval: 10
    checkpoint: null
    resume: null
